appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: JhIiAq6Rm+bcdnDnzXpXZFdGKL52AW6r5nsx7Y9dqHgoqNK3bg3L6TWkVmHLPZXQTDv0Z5VgPSssOKR9LaUSBFXEqmmPtGfNohULNBppbz/aEUc00CrUIRZbzJZad32Vu/UaEZQnPE3OSJ/9iKP9j2dMRenFb85ZmdV4YhR4vuimoJlxhbBWX6uhzJVsub7R1ZAncAuqaqoGwY5tQg1hv7VR58mLrSNeEF5k0uNpQfDuK0f4GiI9Z3VPI7RfBUUk+Hmazk5WhVc5QGsWzdLxiBfYvinI4TAEENtDlMq6/kzGqbu0Ihyy0tDrlCTcXS5/EI5pTZN7OyUnFcOCYAXtE57YLGaZ/TqB9eHUqBeGK2znaa2zxhtr8AWJ/h2/A9X79vTUPVXpVhM7x6Dc2I3NsGiU+p/eRHlxZbub2DwgOfRAJFDnb7TG3yLRS2d1HeVDf4bC/fRKOu9WNtcHjp8RqjRVL4gifTI01cQ0zmMdE6e/xMvTDbZCZVoIzV7EDNXXYhg4L7At4p1TSXYByxbUSoMihufNE5MsbIX3bVGL0NwLsgNwW96b+cIKsXfn0A8Hi1Ngb3RxE8GCK+5coZgUFsI8JuSqW7uk1YCDiEJtwdQtF9mlqZYD8oykd/B9/VdeFcVb9ZG49fhK6xUIEQ61uLKQIhV7Uec0ebiltKCiECo=
